import type { APIRoute } from "astro";
import citiesData from "../../scripts/cities.json";
import { execRoles } from "../data/exec-roles.mjs";
import { metros } from "../data/metros.mjs";
import { guides } from "../data/guides.mjs";

// Legacy occupations generated by the original site (kept in sync with the
// list in src/pages/salary/[occupation]/[location].astro).
const legacyOccupations = [
  "software-developer", "registered-nurse", "financial-analyst", "teacher",
  "mechanical-engineer", "marketing-manager", "accountant", "data-scientist",
  "electrician", "physical-therapist", "sales-manager", "human-resources-manager",
  "graphic-designer", "truck-driver", "dentist", "lawyer", "pharmacist",
  "civil-engineer", "real-estate-agent", "cybersecurity-analyst",
];

export const GET: APIRoute = ({ site }) => {
  const base = (site?.href ?? "https://salary-site-49i.pages.dev/").replace(/\/$/, "");
  const today = new Date().toISOString().slice(0, 10);

  const urls: { loc: string; priority: string }[] = [
    { loc: `${base}/`, priority: "1.0" },
    { loc: `${base}/newsletter`, priority: "0.6" },
  ];

  for (const g of guides) {
    urls.push({ loc: `${base}/guides/${g.slug}`, priority: "0.9" });
  }
  for (const role of execRoles) {
    for (const metro of metros) {
      urls.push({ loc: `${base}/salary/${role.slug}/${metro.slug}`, priority: "0.8" });
    }
  }
  for (const occ of legacyOccupations) {
    for (const city of citiesData as { slug: string }[]) {
      urls.push({ loc: `${base}/salary/${occ}/${city.slug}`, priority: "0.6" });
    }
  }

  const body =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    urls
      .map(
        (u) =>
          `  <url><loc>${u.loc}</loc><lastmod>${today}</lastmod><priority>${u.priority}</priority></url>`
      )
      .join("\n") +
    `\n</urlset>\n`;

  return new Response(body, {
    headers: { "Content-Type": "application/xml; charset=utf-8" },
  });
};
